### ISSUE TITLE
consider using node-sp-auth

### ISSUE THREAD

**Issue by johnnliu** [garrytrinder/phantomjs-office365#1]
In the years since my fake way of putting username/password into the login box and click login, there's been advances!

https://github.com/s-KaiNet/node-sp-auth

node-sp-auth should be able to login with username/password and retrieve a working fedauth token.  use that cookie in phantomjs to continue the session.

"should work"

**Comment by garrytrinder** [comment]
I did look into the Azure AD token route at first for this but didn't get anywhere with it

I got a valid access token back from Azure AD for SharePoint Online, I could use this token in the Authorization header to call the standard SharePoint REST endpoints with no problems, but when requesting a SharePoint page directly, "/SitePages/Home.aspx" I just kept getting "401 Unauthorized".

**Comment by johnnliu** [comment]
https://twitter.com/johnnliu/status/892221440233046016 notes.

**Comment by garrytrinder** [comment]
Closing issue in preference of [Headless Chrome](https://github.com/johnnliu/headless-chrome-o365) solution
