### ISSUE TITLE
consider supporting chrome headless

### ISSUE THREAD

**Issue by johnnliu** [garrytrinder/phantomjs-office365#2]
since Google Chrome will now implement headless browser directly in Chrome, the PhantomJS creator has sunset the project.

going forward, consider using Chrome directly.  I'm not sure where the feature parity is at.

**Comment by garrytrinder** [comment]
Started looking into this and although it will be possible to move over now, for me there are too many gaps in Chrome Headless currently, such as no typings and missing features. Certainly something to look at migrating to over the coming months as Chrome Headless becomes more stable.

Ref: [Using headless Chrome as an automated screenshot tool](https://medium.com/@dschnr/using-headless-chrome-as-an-automated-screenshot-tool-4b07dffba79a)

I'll close this and add as a task in the project.

**Comment by garrytrinder** [comment]
Just realised that the example code was run on Linux, currently there is no Windows Support for Headless, so this a non starter for me.

There is an open issue on Chromium Bugs for this
[Make headless work on Windows](https://bugs.chromium.org/p/chromium/issues/detail?id=686608)

**Comment by johnnliu** [comment]
https://twitter.com/johnnliu/status/892219540196556801 notes.  v60 beta is now available on Windows

**Comment by garrytrinder** [comment]
@johnnliu I've just revisited this, I must have liked your comment then totally forgot about it, have you looked into it on Windows much? The documentation is still very Linux based.

**Comment by garrytrinder** [comment]
Closing issue in preference of [Headless Chrome](https://github.com/johnnliu/headless-chrome-o365) solution
